### PR TITLE
luyten: migrate from core

### PR DESCRIPTION
**Pull request by ilovezfs**
Goes together with https://github.com/Homebrew/homebrew-core/pull/3428.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 any idea why this didn't generate bottles?

**Comment by DomT4** [comment]
`bottle :unneeded` 😉

**Comment by ilovezfs** [comment]
Ah thought this one had bottles! Thanks.

**Comment by DomT4** [comment]
Looks like the bottle job was having a tantrum, albeit non-fatal, though. Apparently `games` got stuck doing a `rebase` at some point:

```
No stash found.
Error: /Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Taps/homebrew/homebrew-games/rom-tools.rb:51: syntax error, unexpected <<, expecting keyword_end
<<<<<<< e1717e3dfd0ac79e524d5aae8dceca66152fe77c
  ^
/Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Taps/homebrew/homebrew-games/rom-tools.rb:54: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Taps/homebrew/homebrew-games/rom-tools.rb:57: syntax error, unexpected >>, expecting keyword_end
>>>>>>> rom-tools 0.176
  ^
/Users/brew/Jenkins/jobs/Homebrew Bottles/workspace/Library/Taps/homebrew/homebrew-games/rom-tools.rb:57: syntax error, unexpected tFLOAT, expecting keyword_do or '{' or '('
```

That's fixed now, at least.

**Comment by ilovezfs** [comment]
That's weird. That upgrade seemed to have gone smoothly:
https://github.com/Homebrew/homebrew-games/commit/dd797321e23fe0c066d6578e8dd3512fdcc198f6
https://github.com/Homebrew/homebrew-games/commit/e1717e3dfd0ac79e524d5aae8dceca66152fe77c

**Comment by DomT4** [comment]
Has happened a few times with the bottle job recently. Unsure if there's a deeper underlying issue yet.

**Comment by ilovezfs** [comment]
@DomT4 @MikeMcQuaid Seems possible the fix in https://github.com/Homebrew/brew/commit/326039763276b2a38b8fcccea0be4a31493a6bda didn't work for the bottle jobs, but the same Jenkins issue/regression afflicts them.

**Comment by MikeMcQuaid** [comment]
@ilovezfs The bottle jobs don't run that code.

**Comment by ilovezfs** [comment]
@MikeMcQuaid Right, I'm just wondering if the change in Jenkins behavior that you were referring to here https://github.com/Homebrew/brew/issues/515#issuecomment-232937784 is the culprit in this case too. But perhaps these conflicts have some other root cause.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Yeh, probably. Still on my list to get this `Jenkinsfile` happening.

**Pull request closed without merging**
