### PR TITLE
mikutter 3.4.4 (new formula)

### PR DESCRIPTION
**Pull request by midchildan**

### CODE REVIEW

**Comment by midchildan** [comment]
Sorry, I first didn't get what the warning about redundant versions meant. It is now fixed.

**Comment by midchildan** [comment]
Seems to have triggered some Homebrew bugs after rebasing.
Homebrew/brew#1209
Homebrew/homebrew-core#5413

**Comment by ilovezfs** [comment]
@midchildan yeah it'll be fixed by https://github.com/Homebrew/brew/pull/1210#issuecomment-250957333 as soon as that's :green_apple: and I merge it.

**Comment by midchildan** [comment]
Thanks. I put some flags to get debug output in acfcf7b, should I remove it?

**Comment by ilovezfs** [comment]
@midchildan probably so.

**Comment by midchildan** [comment]
Some people are currently encountering issues with the bottled version of gdk-pixbuf 2.36.0, a formula mikutter depends on (Homebrew/homebrew-core#5482). If people do experience crashes due to this problem, this can be mitigated by reinstalling gdk-pixbuf from source with `brew reinstall gdk-pixbuf` . Should I document this problem in the formula?

**Comment by midchildan** [comment]
All problems fixed.

**Comment by midchildan** [comment]
Should I move this PR to homebrew-core, following #34 and Homebrew/homebrew-core#5743 ?

**Comment by midchildan** [comment]
Ping

**Comment by midchildan** [comment]
Moving to Homebrew/homebrew-core#6258

**Pull request closed without merging**
