### PR TITLE
threadscope: modernize formula and fix the build

### PR DESCRIPTION
**Pull request by ilovezfs**
threadscope: modernize formula and fix the build

- modernize the formula by using `install_cabal_package`
- avoid unnecessary reinstalls so that it doesn't attempt to install gtk without the `have-quartz-gtk` flag, leading to build failure

### CODE REVIEW

**Comment by ilovezfs** [comment]
Expecting to see
```
[ 22 of 209] Compiling Graphics.UI.Gtk.Embedding.Plug ( dist/dist-sandbox-bc2c08c6/build/Graphics/UI/Gtk/Embedding/Plug.hs, dist/dist-sandbox-bc2c08c6/build/Graphics/UI/Gtk/Embedding/Plug.o )

Graphics/UI/Gtk/Embedding/Plug.chs:120:6: error:
    • Couldn't match expected type ‘Ptr ()’
                  with actual type ‘Maybe DrawWindow’
    • In the first argument of ‘gtk_plug_new’, namely
        ‘(fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’
      In the second argument of ‘($)’, namely
        ‘gtk_plug_new
           (fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’
      In the second argument of ‘($)’, namely
        ‘liftM (castPtr :: Ptr Widget -> Ptr Plug)
         $ gtk_plug_new
             (fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’

Graphics/UI/Gtk/Embedding/Plug.chs:137:6: error:
    • Couldn't match expected type ‘Ptr ()’
                  with actual type ‘Maybe DrawWindow’
    • In the second argument of ‘\ (Display arg1) arg2
                                   -> withForeignPtr arg1
                                      $ \ argPtr1 -> gtk_plug_new_for_display argPtr1 arg2’, namely
        ‘(fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’
      In the second argument of ‘($)’, namely
        ‘(\ (Display arg1) arg2
            -> withForeignPtr arg1
               $ \ argPtr1 -> gtk_plug_new_for_display argPtr1 arg2)
           display
           (fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’
      In the second argument of ‘($)’, namely
        ‘liftM (castPtr :: Ptr Widget -> Ptr Plug)
         $ (\ (Display arg1) arg2
              -> withForeignPtr arg1
                 $ \ argPtr1 -> gtk_plug_new_for_display argPtr1 arg2)
             display
             (fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’

Graphics/UI/Gtk/Embedding/Plug.chs:151:3: error:
    • Couldn't match type ‘Ptr ()’ with ‘Maybe DrawWindow’
      Expected type: IO (Maybe DrawWindow)
        Actual type: IO (Ptr ())
    • In the second argument of ‘($)’, namely
        ‘(\ (Plug arg1)
            -> withForeignPtr arg1 $ \ argPtr1 -> gtk_plug_get_id argPtr1)
           (toPlug self)’
      In the expression:
        liftM toNativeWindowId
        $ (\ (Plug arg1)
             -> withForeignPtr arg1 $ \ argPtr1 -> gtk_plug_get_id argPtr1)
            (toPlug self)
      In an equation for ‘plugGetId’:
          plugGetId self
            = liftM toNativeWindowId
              $ (\ (Plug arg1)
                   -> withForeignPtr arg1 $ \ argPtr1 -> gtk_plug_get_id argPtr1)
                  (toPlug self)
cabal: Leaving directory '/var/folders/w6/9r0nb9011glb8fdz__srd78c0000gq/T/cabal-tmp-10126/gtk-0.14.3'
cabal: Error: some packages failed to install:
gtk-0.14.3 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by ilovezfs** [comment]
Filed an upstream issue report here: https://github.com/haskell/ThreadScope/issues/57

**Comment by ilovezfs** [comment]
@MikeMcQuaid @DomT4 I think this actually broke due to some changes in the behavior of Cabal 1.24, not anything to do with GHC 8, but I've fixed it now.

**Comment by MikeMcQuaid** [comment]
👍

**Comment by ilovezfs** [comment]
Downstream build seems to fail both with "retry" and "rebuild", so not sure what's up with that.

**Comment by ilovezfs** [comment]
http://bot.brew.sh/job/Homebrew%20Bottles/50702/

**Comment by MikeMcQuaid** [comment]
@ilovezfs Bintray API failure. Might get more luck running it locally.

**Comment by ilovezfs** [comment]
Seems to be in https://github.com/BrewTestBot/homebrew-gui/commits/master and not in https://github.com/BrewTestBot/homebrew-gui/tree/pr-10, which doesn't exist.

https://github.com/BrewTestBot/homebrew-gui/compare/homebrew:master...pr-10 is indeed a bogus link

**Comment by DomT4** [comment]
Looks like this may be happening with http://bot.brew.sh/job/Homebrew%20Bottles/50690/console as well from [dupes](https://github.com/Homebrew/homebrew-dupes/pull/614). Wonder if related to the recent switch to JSON or related to the ridiculous CI fun lately _(Hard to tell due to the limited number of bottle builds we keep)_.

Same situation in [science](http://bot.brew.sh/job/Homebrew%20Bottles/50693/console) as well, by the looks of it.

**Comment by ilovezfs** [comment]
Seems likely to be a regression due to https://github.com/Homebrew/brew/commit/6ba466f5d858c5e6f9d162c11ec03134df6e686e

**Comment by ilovezfs** [comment]
I think I see the problem.
```
bintray":{"package":"homebrew/gui/threadscope","repository":"bottles-gui"}}}
```
It's using `homebrew/gui/threadscope` to construct the URL.
https://api.bintray.com/packages/homebrew/bottles-gui/homebrew/gui/threadscope

but I think the URL is supposed to be
https://api.bintray.com/packages/homebrew/bottles-gui/threadscope

**Pull request closed without merging**
