### PR TITLE
X11 migration

### PR DESCRIPTION
**Pull request by tschoonj**
Migrating some formulas from X11 to gui (and several other Homebrew taps).

This is a work in progress and should not be merged until Homebrew/homebrew#47924 is ready.

### CODE REVIEW

**Comment by DomT4** [comment]
@mikemcquaid Need to hook this tap up to CI for bottles/etc. Can you hunt that down when you have a moment, Cheers :heart:

**Comment by DomT4** [comment]
Can you take a look at the two build failures here @tschoonj? http://bot.brew.sh/job/Homebrew%20GUI%20Pull%20Requests/5/#showFailuresLink

If you wanted to get the audits as well that'd be great but the install problems are a blocker.

**Comment by tschoonj** [comment]
The kernagic issue should be fixed with this commit. The threadscope problem appears to be a Homebrew-haskell formula thing that is my beyond my skill set :smile:

**Comment by mikemcquaid** [comment]
@DomT4 Was already hooked up but just wasn't posting status. Fixed now.

**Comment by tschoonj** [comment]
Anything happening here?

**Comment by mikemcquaid** [comment]
@tschoonj Are any of these legit failures: http://bot.brew.sh/job/Homebrew%20GUI%20Pull%20Requests/8/version=el_capitan/console? If not, happy to merge as-is.

**Comment by DomT4** [comment]
`threadscope` isn't building, which is the problem.

**Comment by tschoonj** [comment]
The `threadscope` issue looks to me like a Homebrew issue:

````
==> cabal install --jobs=4 --prefix=/usr/local/Cellar/threadscope/0.2.7
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/gettext/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/libffi/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/icu4c/lib'
clang: warning: argument unused during compilation: '-L/usr/local/lib'
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries'
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/threadscope20160118-39860-752t13/threadscope-0.2.7/.cabal-sandbox
Configuring threadscope-0.2.7...
Building threadscope-0.2.7...
Installed threadscope-0.2.7
Error: undefined local variable or method `cabal_clean_lib' for #<Formulary::FormulaNamespace58e017ed476366d95621ec9ba5f08457::Threadscope:0x007fde43aa8f10>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-gui/threadscope.rb:39:in `install'
/usr/local/Library/Homebrew/build.rb:130:in `block in install'
/usr/local/Library/Homebrew/formula.rb:926:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1567:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:92:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1557:in `stage'
/usr/local/Library/Homebrew/formula.rb:922:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'
````

No idea how to fix it though

**Comment by mikemcquaid** [comment]
@tschoonj Looks like we (naughtily) removed that method from the DSL. It can be replaced like so: https://github.com/Homebrew/homebrew/commit/463f535fc78811e0279b719cfca06509b2f8b433

**Comment by DomT4** [comment]
Oh whoops. That should have probably been aliased or something temporarily. OP did fix everything else in the core at the same time as the DSL change but evidently things in taps using our helper methods have been broken.

**Comment by mikemcquaid** [comment]
@DomT4 Yeh, I'm wondering if we should add that method back as a noop to avoid breaking things?

**Comment by DomT4** [comment]
Seems reasonable. Doing a quick search for `cabal_clean_lib` on GitHub shows plenty of external taps/custom formulae using that helper.

**Comment by mikemcquaid** [comment]
https://github.com/Homebrew/homebrew/pull/48479

**Comment by mikemcquaid** [comment]
Added back in https://github.com/Homebrew/homebrew/pull/48479. When CI is quiet this can be requeued.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
_Sigh_. Mavericks killed the build. I'll queue this up again overnight with a ridiculously, hilariously long timeout and maybe we'll have some luck there.

**Comment by DomT4** [comment]
@mikemcquaid Any idea why I can't pull bottles here?

```
~> brewpb https://github.com/Homebrew/homebrew-gui/pull/2
######################################################################## 100.0%
==> Applying patch
Applying: geeqie: migrate from x11
Applying: gsmartcontrol: migrate from x11
Applying: gtk-chtheme: migrate from x11
Applying: gtkwave: migrate from x11
Applying: hexchat: migrate from x11
Applying: inkscape: migrate from x11
Applying: iptux: migrate from x11
Applying: iptux: remove x11 dependency
Applying: kernagic: migrate from x11
Applying: terminator: migrate from x11
Applying: threadscope: migrate from x11
Applying: upnp-router-control: migrate from x11
Applying: xchat: migrate from x11
Applying: xournal: migrate from x11
Applying: cardpeek: migrate from x11
Applying: cardpeek: remove unnecessary x11 dependency
Applying: easy-tag: migrate from x11
Applying: gobby: migrate from x11
Applying: klavaro: migrate from x11
Applying: meld: migrate from x11
Applying: smartsim: migrate from x11
Applying: transmission-remote-gtk: migrate from x11
Applying: smartsim: remove unnecessary x11 dependency
Applying: transmission-remote-gtk: remove unnecessary x11 dependency
Applying: kernagic: remove unnecessary x11 dependency
Applying: kernagic: fix build failure with older clang versions
Applying: easy-tag 2.4.1
==> Patch closes issue #2
==> Patch changed:
 cardpeek.rb                |  36 +++++++++++++
 easy-tag.rb                |  67 ++++++++++++++++++++++++
 geeqie.rb                  |  35 +++++++++++++
 gobby.rb                   | 104 +++++++++++++++++++++++++++++++++++++
 gsmartcontrol.rb           |  62 ++++++++++++++++++++++
 gtk-chtheme.rb             |  32 ++++++++++++
 gtkwave.rb                 |  37 +++++++++++++
 hexchat.rb                 |  68 ++++++++++++++++++++++++
 inkscape.rb                |  68 ++++++++++++++++++++++++
 iptux.rb                   |  23 +++++++++
 kernagic.rb                |  35 +++++++++++++
 klavaro.rb                 |  28 ++++++++++
 meld.rb                    |  38 ++++++++++++++
 smartsim.rb                |  25 +++++++++
 terminator.rb              |  71 +++++++++++++++++++++++++
 threadscope.rb             |  45 ++++++++++++++++
 transmission-remote-gtk.rb |  15 ++++++
 upnp-router-control.rb     |  82 +++++++++++++++++++++++++++++
 xchat.rb                   | 101 ++++++++++++++++++++++++++++++++++++
 xournal.rb                 | 126 +++++++++++++++++++++++++++++++++++++++++++++
 20 files changed, 1098 insertions(+)
```

They're being generated, available on Bintray, the BTB fork is the right amount of commits ahead, I added it to the official taps list in https://github.com/Homebrew/homebrew/commit/2d6cdcc292196108a65df2ec00d7d71606424ac8. Not sure what else I'm missing :confused:. It's not even trying to pull bottles.

**Comment by UniqMartin** [comment]
> It's not even trying to pull bottles.

I guess you're trying to do this form a Homebrew installation with a tapped `homebrew/x11`? Fixed in Homebrew/homebrew@04ed8eb3da7570ec91640346d22b61372833e631.

The problem was [in this part of `pull.rb`](https://github.com/Homebrew/homebrew/blob/f7f56a77/Library/Homebrew/cmd/pull.rb#L97-L111) where it collects the changed formulae in the `changed_formulae` array, but because the formulae in question are now in both the `homebrew/gui` and `homebrew/x11` tap and the code uses an unqualified formula name, a `TapFormulaAmbiguityError` exception is thrown (and silently ignored due to the catch-all `rescue Exception`). Consequently, `changed_formulae` remains empty and `fetch_bottles` is never set to `true`.

**Comment by DomT4** [comment]
@UniqMartin Yeah, I was. That's a slightly surprising issue point because I've definitely pulled formulae from one tap to another (albeit where that tap _already_ had other formulae present) in Homebrew without encountering the failure before now. But your fix seems to work perfectly, so I'll colour myself mildly confused on why I've not seen this before but thankful to you for fixing it :bow:.

Merged in an absolute hoard of commits. Thanks for pressing to get this done @tschoonj; appreciate the amount of effort these tap migrations need and the amount of _fun_ they cause.

**Pull request closed without merging**
