### PR TITLE
Delete unused formulae

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Delete all homebrew/gui formulae that show no installations since analytics records began.

### CODE REVIEW

**Comment by miclf** [comment]
Hello,

I actually need one of these formulae. Is there any way to, for example, copy it somewhere on my machine and then tell Homebrew to also look there when looking for available formulae so that it would be able to install it as if it was coming from an official tap?

Thanks in advance for any help!

**Comment by dunn** [comment]
@miclf which formula?

**Comment by MikeMcQuaid** [comment]
@miclf (as we may re-add it)

**Comment by miclf** [comment]
@dunn @MikeMcQuaid It’s Klavaro.

Note that I’m not asking to re-add it. If I’m the only one who needs this formula, I would be fine with an alternate way to make my Homebrew installation able to use it.

**Comment by MikeMcQuaid** [comment]
@miclf Reverted/readded in f2de0c0.

**Comment by miclf** [comment]
@MikeMcQuaid Thanks!

**Pull request merged**
